org: bishal1234
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: post
          cors: true
  emailList:
    handler: index.emailList
    events:
      - http:
          path: /emailList
          method: post
          cors: true
